### ISSUE TITLE
[secrets-store-csi-driver-provider-gcp] Is this related at all to the official GCP helm chart?

### ISSUE THREAD

**Issue by red8888** [portefaix/portefaix-hub#316]
### Is your feature request related to a problem ?

no

### Describe the solution you'd like.

It looks like they started an official chart, but I cannot find out if they published it to a repo yet: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/tree/main/charts

Is this chart just a copy of their chart or was it hand rolled by portefaix?

### Describe alternatives you've considered.

I'd prefer to use helm if possible, but want to know how this chart was created first because its not official. Otherwise I'd just install directly from github with kubectl apply: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/deploy/provider-gcp-plugin.yaml

Thanks!

**Comment by nlamirault** [comment]
@red8888 hi, i create this chart because no official chart was available. When i could use the official chart (repo, artifacthub, ...), i will set this chart as deprecated.
