### ISSUE TITLE
Use default labels and annotations

### ISSUE THREAD

**Issue by danygielow** [portefaix/portefaix-hub#472]
### Is your feature request related to a problem ?

Hi,

I like this project and would like to use these Helm Charts.
Unfortunately the used labels and annotations are not standard for grafana to discover the configmaps.

### Labels
The default label is `grafana_alert`
https://github.com/grafana/helm-charts/blob/grafana-6.55.1/charts/grafana/values.yaml#L821

### Labels
The default label is `grafana_dashboard`
https://github.com/grafana/helm-charts/blob/grafana-6.55.1/charts/grafana/values.yaml#L860

This is used by some other helm charts already:
https://github.com/grafana/loki/blob/v2.8.1/production/helm/loki/values.yaml#L474

https://github.com/prometheus-community/helm-charts/blob/f114f3fa39a28d2e41d90f743a82ac310469d93b/charts/kube-prometheus-stack/values.yaml#L824

### Folder Annotations
The default label is `k8s-sidecar-target-directory`  . This is because https://github.com/kiwigrid/k8s-sidecar is used.

### Describe the solution you'd like.

To be able to stay backwards compatible with the charts in this repo, it would be great to be able to override the names for the discovery label and folder annotation or add labels and annotations to the config maps.

### Describe alternatives you've considered.

I tried to override the labels and annotations or add labels and annotations. But that wasn't possible with the current charts.

One could theoretically override the labels and annotations in non-portefaix charts, but I would only consider this a workaround, that doesn't address the issue.

**Comment by nlamirault** [comment]
I configure the sidecar like that: https://github.com/portefaix/portefaix-kubernetes/blob/master/gitops/argocd/charts/monitoring/grafana/values.yaml#L277

You could override the labels used.

**Comment by danygielow** [comment]
> I configure the sidecar like that: https://github.com/portefaix/portefaix-kubernetes/blob/master/gitops/argocd/charts/monitoring/grafana/values.yaml#L277
> 
> You could override the labels used.

I could do that, but I would have to change the labels used in my other charts, that already create ConfigMaps für Grafana Dashboards etc. 
I already use loki, mimir-distributed and kube-prometheus-stack charts, that install dashboards and datasources with the default labels and annotations. It would be great if I could only change the label and annotation names in the tempo-mixin portefaix chart instead of all the other charts.
